version: '3'

services:
  database:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  api:
    build:
      context: ./api
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ./api:/var/www

  nginx:
    image: openresty/openresty:alpine
    volumes:
      - ./api:/var/www
      - ./nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log
    depends_on:
      - api
    ports:
      - "8080:80"

  client:
    image: node:14
    working_dir: /usr/src/app
    volumes: 
      - ./client:/usr/src/app
    depends_on:
      - nginx
    ports:
      - "3000:3000"
    command: [sh, -c, "npm install && npm start"]

