version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-10.5.8
    expose:
      - 9000
    restart: 'unless-stopped'
    working_dir: /var/www

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod

  nginx:
    build:
        context: .
        dockerfile: ./nginx/Dockerfile.prod
    depends_on:
      - api
      - client
    expose:
      - 8080
      - 8081
    restart: 'unless-stopped'
    working_dir: /var/www
