version: '3'

services:
  database:
    image: mariadb:10.5.8
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    restart: 'unless-stopped'

  api:
    build:
      context: ./api
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-10.5.8
      - CORS_ALLOW_ORIGIN=*
    expose:
      - 9000
    restart: 'unless-stopped'
    user: '1000:1000'
    volumes:
      - ./api:/var/www
    working_dir: /var/www

  nginx:
    image: nginx:1.19-alpine
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: 'unless-stopped'
    volumes:
      - ./api/public:/var/www/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    working_dir: /var/www

  client:
    image: node:14
    working_dir: /usr/src/app
    volumes: 
      - ./client:/usr/src/app
    depends_on:
      - nginx
    ports:
      - "3000:3000"
    command: ["npm", "start"]
