version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod

  nginx:
    build:
        context: ..
        dockerfile: ./nginx/Dockerfile.prod
    depends_on:
      - api
      - client
