FROM nginx:1.19-alpine 

COPY --from=build_api /var/www/api/public /var/www/api/public/
COPY --from=build_client /usr/src/app/build var/www/client
COPY ./build/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./build/nginx/conf.d/ /etc/nginx/conf.d

EXPOSE 8080 8081
